# Generated by Django 6.0.6 on 2026-06-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('in-progress', 'in-progress'), ('completed', 'completed')], max_length=50, null=True),
        ),
    ]
